apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi  # Adjust based on your dataset size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/chromadb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi